### ISSUE TITLE
Allow a feature flag to build for iOS 

### ISSUE THREAD

**Issue by seivan** [germangb/minimp3-rs#16]
It would be necessary to set some defines (which ones I'm not sure of yet) to get this to build (and by proxy Rodio) for iOS.

https://github.com/lieff/minimp3/blob/eaa7e4d3f7ae790c02ffe88442cf333c6b5ffe58/player/stb_image.h#L213

**Comment by seivan** [comment]
Related https://github.com/RustAudio/rodio/issues/194

**Comment by seivan** [comment]
Nevermind, it seems fixed now.

**Comment by germangb** [comment]
Still it may be worth defining feature flags to mirror some if not all of the `#define`s. or perhaps using env variables with names such as `MINIMP3_<define_name>`.
