### ISSUE TITLE
Crates.io version is late compared to the documentation version

### ISSUE THREAD

**Issue by abocquet** [germangb/minimp3-rs#22]
The readme on Github invites to install version `0.4`, but crates.io version only goes up to `0.3.5`, so version `0.4` isn't installable. This prevents from working with the `async_tokio` feature.

<img width="218" alt="Capture d’écran 2020-08-23 à 19 55 29" src="https://user-images.githubusercontent.com/4300678/90985195-9a8e2880-e57a-11ea-863b-cc9a5d6c1d44.png">

<img width="174" alt="Capture d’écran 2020-08-23 à 19 56 05" src="https://user-images.githubusercontent.com/4300678/90985208-bd204180-e57a-11ea-8929-efd15a015e65.png">

**Comment by germangb** [comment]
`0.4.0` is not published. The `async_tokio` feature is disabled by default
